version: "3.6"
services:
  application:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
    - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    ports:
      - "8080:8080"
    links:
      - database:postgres
    depends_on:
      - database
    networks:
    - dancing-school-network

  database:
    image: postgres
    env_file:
    - .env
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
    - dancing-school-network

networks:
  dancing-school-network:
    driver: bridge

volumes:
  dancing-school:
    driver: local