# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.DeleteModel(
            name='Sosi',
        ),
    ]
