# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180805_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='GalleryItem',
            new_name='PhotoItem',
        ),
    ]
