# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-05 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180805_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='src',
            field=models.CharField(max_length=500),
        ),
    ]
