# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180805_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPhotoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='upload/')),
                ('image_2', models.ImageField(upload_to='upload/')),
                ('teacher_name', models.CharField(max_length=500)),
            ],
        ),
    ]
